### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor

### ISSUE THREAD

**Issue by kmthinkingrock** [tbroyer/gwt-maven-plugin#62]
I am trying to migrate to this plugin and I am getting an internal compiler error. I am not sure what information is of use. It is a multi module project. I made an attempt to root out conflicting dependencies. There are a lot of server libs since its a combined client+server project, I guess ..

```
[INFO] [ERROR] Unexpected internal compiler error

[INFO] java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor

[INFO]  at com.google.gwt.dev.javac.CompiledClass.getSignatureHash(CompiledClass.java:165)

[INFO]  at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:41)

[INFO]  at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:36)

[INFO]  at com.google.gwt.dev.javac.Dependencies.resolve(Dependencies.java:100)

[INFO]  at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:352)

[INFO]  at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)

[INFO]  at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)

[INFO]  at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)

[INFO]  at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)

[INFO]  at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)

[INFO]  at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)

[INFO]  at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)

[INFO]  at com.google.gwt.dev.Compiler.compile(Compiler.java:204)

[INFO]  at com.google.gwt.dev.Compiler.compile(Compiler.java:155)

[INFO]  at com.google.gwt.dev.Compiler.compile(Compiler.java:144)

[INFO]  at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)

[INFO]  at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)

[INFO]  at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)

[INFO]  at com.google.gwt.dev.Compiler.main(Compiler.java:125)

[INFO] Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor

[INFO]  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

[INFO]  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)

[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

[INFO]  ... 19 more


```

**Comment by ibaca** [comment]
I think that you just need to add the gwt-dev dependency. I recommended to add GWT as an import pom dependency too. And, this plugins born to makes multi-module project works correctly, so you can separate client and server dependencies which frequently end up producing dependencies conflicts, so I recommend that you split your project too.

If this doesn't fix the problem, upload your pom 😉.

**Comment by tbroyer** [comment]
@kmthinkingrock Check your dependency tree (start with `mvn dependency:tree`), something must be excluding (?) ASM or replacing it with a version without that class. But I'd suggest moving to a multi-module project first, cleanly separating client and server dependencies, then only switch plugin. You may also want to try out 1.0-SNAPSHOT of this plugin and run Maven with debug logs (`mvn -X …`), that way you can see the exact classpath used to invoke GWT.

(@ibaca gwt-dev must be here already, as all those classes in the stacktrace come from it)

**Comment by kmthinkingrock** [comment]
Unfortunately I don't know how to cleanly separate client and server dependencies, without building two WARs. I won't be able to investigate this until next week. I didn't understand the multi-module archetype, but I only spent 30 seconds looking at it. Thanks for the assistance so far, I will look into this next week.

**Comment by branflake2267** [comment]
This should solve this issue. 
```
<!-- GWT BOM -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.gwt</groupId>
        <artifactId>gwt</artifactId>
        <version>${gwt.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!-- GWT -->
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-user</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-dev</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>

**Comment by carlolf** [comment]
Just found this thread because I met the same compiler error - but note, I'm using not Maven, but Gradle with Github's steffenschaefer/gwt-gradle-plugin. I have gwt-dev and gwt-user on my compile dependencies, but this does not resolve the problem. 

Any Gradle user here who knows how to solve this compiler error?

**Comment by tbroyer** [comment]
@carlolf [`./gradlew dependencies`](https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html#sec:listing_dependencies) or [`./gradlew dependencyInsight --dependency asm`](https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html#sec:dependency_insight) should help you find which ASM version you're using (if it's not missing) and where it comes from.

Please followup to [StackOverflow](https://stackoverflow.com/questions/tagged/gwt) or the [GWT forum](https://groups.google.com/forum/#!forum/google-web-toolkit).
